Exclude test pack from index
StackStorm-Exchange/stackstorm-test pull request #16
Opened 2021-02-10 16:20 UTC by cognifloyd

This allows us to use full pack CI in this test pack without actually adding it to the index.

Depends on StackStorm-Exchange/ci#108

2021-02-10 16:33 UTC, armab requested changes
Please just update the deploy branch back to `master` and it'll make it non-deploy as before.
That'll revert existing behavior.

2021-02-10 16:45 UTC, cognifloyd commented
No. That would break the weekly test runs which we need to ensure PATs stay active. Also, that relies on an obscure side effect instead of making skipping the index explicit.

2021-02-10 17:52 UTC, blag commented
Do we support deploying to Exchange from a non-`master` branch? If so, we should keep this, and just make sure that we add a deploy key to the CircleCI config for this repo, since that actually _prevents_ the deploy step from pushing updated changes to the index.

If we do _not_ support deploying to Exchange from a non-`master` branch, then we should add some comments to the deploy script to let future developers (but really, future me) know why that's hard-coded.

This pack and the test2 pack both exist to test installing non-`master` default branch, but I truly don't know if that includes deploying these packs to Exchange. I don't know what the intent has been in the past.

2021-02-10 18:27 UTC, cognifloyd commented
I want to use `test` and `test2` for the purpose listed in the readme:
https://github.com/StackStorm-Exchange/stackstorm-test2/blob/a82739da92113b401d09192743cf2eb7296e2b7b/README.md#L3

To test changes to the pack CI system itself, including changes to the `deploy` step. But I can't do that if we [purposely] break the CI config.

2021-02-10 18:35 UTC, blag commented
I think, possibly in addition to or instead of using a flag to disable write operations for the deploy step of the test packs, that we should just ensure that they do not ever have any valid credentials that give them write/push access. That way, if we mess up our script logic and accidentally try to write/push to the index, the lack of a valid write creds will still help prevent it.

2021-02-10 19:03 UTC, cognifloyd commented
I think we could use read-only PATs for test packs: https://github.com/StackStorm-Exchange/ci/pull/107/commits/6b9d512c34463285c7293ef82466945454a5448c

I'm not sure if that will affect the ability to add tags to the pack repo.

2021-02-11 18:21 UTC, armab commented
> If we do not support deploying to Exchange from a non-master branch, then we should add some comments to the deploy script to let future developers (but really, future me) know why that's hard-coded.

I agree. There should be a hint somewhere.

Looks like these test repos never ran the `deploy` script and should not be deployed to Exchange index. We also don't support any non-master branches deployments to Exchange which complements that story.

Because previously CircleCI config defined `master` for deployment while repository used `aaa` the deployment script never ran.

The behavior that changed it 6 days ago is: 
https://github.com/StackStorm-Exchange/stackstorm-test/commit/b684a69747b3828ff7f3563393779234fb209a50#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R95

which was probably best intent.

2021-02-12 01:09 UTC, cognifloyd commented
Closing this in favor of a variable added via CircleCI itself.
https://github.com/StackStorm-Exchange/ci/pull/108#issuecomment-777746129

2021-02-12 01:09 UTC, closed without merging